### ISSUE TITLE
PyGraph compose with oneself creates RuntimeError

### ISSUE THREAD

**Issue by redfave** [Qiskit/rustworkx#1028]
### Information

- **0.13.2**:
- **3.10.11**:
- **Not installed, using precompiled wheel**:
- **Win 11 x64**:

### What is the current behavior?

Calling the compose method on PyGraph with oneself creates the following error:
`RuntimeError: Already mutably borrowed`

### What is the expected behavior?
To print at least a human friendly error message.
Although from my understanding it should be possible to call compose on the PyGraph oneself.

Background: I'm trying to give the nodes string labels. I don't want to create the Graph node by node and edge by edge with possible labelling, but to use the numpy matrix as input and to label the nodes afterwards. This is what I attempt with the following example, which produces the error.

### Steps to reproduce the problem
```
A = np.matrix([
    [0, 56, 35, 2, 51, 60],
    [56, 0, 21, 57, 78, 70],
    [35, 21, 0, 36, 68, 68],
    [2, 57, 36, 0, 51, 61],
    [51, 78, 68, 51, 0, 13],
    [60, 70, 68, 61, 13, 0]
],dtype= np.float64)

G = rustworkx.PyGraph(multigraph= False).from_adjacency_matrix(A)
node_names_old = G.nodes()
node_names_new = ['L', 'MC', 'NY', 'Pa', 'Pe', 'T']

node_map = {}
for node_idx in range(0, len(node_names_old)):
    # G.contract_nodes([node_idx], node_names_new[node_idx])
    node_map.setdefault(node_idx, (node_idx, node_names_new[node_idx]))

G.compose(G, node_map)
```

**Comment by mtreinish** [comment]
The underlying issue here that's causing the exception is actually a limitation in the Rust<->Python interface. Rust needs to be able to track the ownership of objects and when we mix in Python which doesn't have a concept of ownership things can get a bit tricky. In this case what happens is PyO3 is detecting that your `G` object is already being used and then is also getting passed as an input to `compose()` which isn't safe in rust (or arguably python either), so it's raising an exception to prevent this. The only path around this is to explicitly make a copy of the graph object, so doing something like:

`G.compose(G.copy(), node_map)`

instead of using the shared reference to the same G. This will create a copy of the graph to compose, which I think is the behavior your expecting here. If you update your code like this it should fix the error you're hitting.

 That all being said, I'm personally not sure I'd expect `G.compose(G, node_map)` to ever work even in pure python it's kind of like doing:

```python
test = [1, 2, 3]
for i in test:
    test.append(test)
```

because you're passing a self reference to something that is mutating itself. Python doesn't block this, but it's an infinite loop. This error is basically what Rust is be protecting against in this case.
 
I do agree that the error message is cryptic, and we should try to improve it, especially as concerns about shared references and mutability are not something a Python programmer is normally worried about. Also, `borrowing` is a very rust term. It would make sense if you're familiar with rust, but the Rust user isn't who sees the error. But, I'm not sure we'll be able to generate a better error message in this case on the rustworkx side, because the error message and exception are coming from [PyO3](https://github.com/PyO3/pyo3) before any rustworkx code gets executed (see [here](https://github.com/PyO3/pyo3/blob/c8fdb806300ff82747f58bcb9ca08abd3da480b4/src/pycell.rs#L302)). We can work with PyO3 though to improve the error message though.

**Comment by IvanIsCoding** [comment]
I second Matthew's solution to make a copy with `G.compose(G.copy(), node_map)`. We can add a note that calling our function with the same graph returns an error, but I am glad it returned an error. The error prompted you to take action, most code out there would lead to some kind of undefined behaviour

**Comment by IvanIsCoding** [comment]
Closing this as Matthew proposed a solution already
