### ISSUE TITLE
Erroneous Reno in tests

### ISSUE THREAD

**Issue by prakharb10** [Qiskit/rustworkx#678]
### Information

- **retworkx version**: 0.11.0
- **Python version**: 3.9.6
- **Rust version**: 1.63.0
- **Operating system**: macOS 12.5.1

### What is the current behavior?
There's a reno placed in the test directories at - https://github.com/Qiskit/rustworkx/blob/main/tests/rustworkx_tests/generators/releasenotes/notes/d-1-heavy-hex-e2e44861dc75009a.yaml

I'm not sure, but I think this is erroneous.

### What is the expected behavior?
Reno should be placed in the `releasenotes` directory.

**Comment by mtreinish** [comment]
This is a good catch. We should fix this, the complexity is that this was included in a release already which means if we simply `git mv` the file to `releasenotes.notes` reno wiill treat this as part of the next release instead of the previous one. I think to fix this we should copy the contents of the release note included in the previous release like: https://github.com/Qiskit/rustworkx/blob/main/releasenotes/notes/0.11/prepare-0.11-af688e532712c830.yaml and remove the stray file. Then when we build release notes the next time it will include the contents in the proper place.

**Comment by prakharb10** [comment]
I think I understand @mtreinish. I'll try to make a PR with the minor fix.
What about something similar to https://github.com/Qiskit/qiskit-terra/pull/8320 in the repo to prevent this in the future?

**Comment by mtreinish** [comment]
Yeah adding the validation job is a good idea, that will prevent this in the future. (and since I'm apparently the typical cause of these issues it'll be good to ensure more discipline on my part)
