### ISSUE TITLE
Consider replacing hashbrown use in core API

### ISSUE THREAD

**Issue by kevinhartman** [Qiskit/rustworkx#911]
### What is the expected enhancement?

Currently, some structs from `hashbrown` are used in the core API (e.g. the [`mapping` parameter of `token_swapper`](https://github.com/Qiskit/rustworkx/blob/c4f0c2e239dc45c1a5c51fc4fe0cc42be5ea9b78/rustworkx-core/src/token_swapper.rs#L410)). As a result, downstream libraries are required to use the same minor version of `hashbrown`, which has proven to be somewhat cumbersome.

Note that by switching to the standard lib equivalents, we may take _some_ perf hit, but perhaps this is worth the UX improvement.

**Comment by IvanIsCoding** [comment]
I don’t think we should swap hashbrown for the one in the standard library, but we should definitely relax the constraints on some dependencies.

rustworkx for Python won’t be affected because we pin our dependencies and have Cargo.lock. rustworkx-core would have modification in its Cargo.toml and maybe we will add some more CI checks. It seems like a reasonable compromise.
